name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    
    - name: Docker login
      uses: azure/container-actions/docker-login@master
      with: 
        username: ${{ secrets.username }} 
        password: ${{ secrets.password }} 
    
    - name: Build and push the Docker image
      run: |
        docker build . --tag sample-image:${{ github.sha }} 
        docker push sample-image:${{ github.sha }} 
